name: ia-ai
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Etapa obrigatoria "Checkout"
        uses: actions/checkout@v4
      - run: echo "Install Python3"
      - name: Install python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: aula
      - name: Install Python libs
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy yfinance
          
